// layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Outfit, Paytone_One } from "next/font/google";
import { AuthProvider } from "./AuthContext"; // Import AuthProvider

const outfit = Outfit({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-outfit",
});

const paytone = Paytone_One({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-paytone",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} ${paytone.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
